services:
    localhost:
        ports:
            - "8080:8080"
            - "8000:8000"
            - "3000:8081"

    nl-portal-backend:
        container_name: nl-portal-backend
        build: ../backend
        network_mode: "service:localhost"
        env_file: imports/backend.env

    nl-portal-frontend:
        container_name: nl-portal-frontend
        build: ../frontend
        network_mode: "service:localhost"
        env_file: imports/frontend.env
