export const config = {
  OIDC_URL: window.OIDC_URL,
  OIDC_REALM: window.OIDC_REALM,
  OIDC_CLIENT_ID: window.OIDC_CLIENT_ID,
  OIDC_REDIRECT_URI: window.OIDC_REDIRECT_URI,
  OIDC_POST_LOGOUT_REDIRECT_URI: window.OIDC_POST_LOGOUT_REDIRECT_URI,
  OIDC_AUTO_IDLE_SESSION_LOGOUT: window.OIDC_AUTO_IDLE_SESSION_LOGOUT,
  OIDC_IDLE_TIMEOUT_MINUTES: window.OIDC_IDLE_TIMEOUT_MINUTES,
  GRAPHQL_URI: window.GRAPHQL_URI,
  REST_URI: window.REST_URI,
};
